contact_links:
  - name: Slack Forum
    url: https://join.slack.com/t/timetabl/shared_invite/zt-1dhr2v791-G0IDTb~kLRXT~0vjmyEtmw
    about: If you'd like to ask more direct questions about using Timetabl, feel free to join our Slack forum.
