import { describe, expect, test } from "vitest";
import { timetableSchema } from "./schemas";

describe("the schema", () => {
  test("parses a timetable with no morning periods", () => {
    const timetable = {
      student: {
        surname: "DOE",
        givenname: "John",
        gender: "M",
        DOB: null,
        roll: "RC.9E",
        BoSNumber: null,
        year: "9",
        years: ["9"],
        studentId: "444125345",
      },
      subjects: [
        {
          title: "9 Design & Technology CZ",
          shortTitle: "D&T CZ",
          teacher: "GIFR",
          subject: "Design & Technology Yr9",
          fullTeacher: "R Gifford",
          year: "9",
          colour: "448ae6",
        },
        {
          title: "9 Sport 9",
          shortTitle: "SP 9",
          teacher: null,
          subject: "Sport Yr9",
          fullTeacher: "",
          year: "9",
          colour: "7f5252",
        },
        {
          title: "9 Values Education A",
          shortTitle: "VED A",
          teacher: "PAUV",
          subject: "Values Education Yr9",
          fullTeacher: "V Paul",
          year: "9",
          colour: "640064",
        },
        {
          title: "9 PDHPE A",
          shortTitle: "PDH A",
          teacher: "HAYB",
          subject: "PDHPE Yr9",
          fullTeacher: "B Hayman",
          year: "9",
          colour: "004040",
        },
        {
          title: "9 Year EFM",
          shortTitle: "YA EFM",
          teacher: "JAMJ",
          subject: "Year Adviser",
          fullTeacher: "J James",
          year: "9",
          colour: "c0c0c0",
        },
        {
          title: "9 History BX",
          shortTitle: "HIS BX",
          teacher: "GENM",
          subject: "History Yr9",
          fullTeacher: "M Genias",
          year: "9",
          colour: "9d9d4f",
        },
        {
          title: "9 Geography A",
          shortTitle: "GEO A",
          teacher: "STEH",
          subject: "Geography Yr9",
          fullTeacher: "H Stephens",
          year: "9",
          colour: "008080",
        },
        {
          title: "9 Mathematics 5.3 A",
          shortTitle: "MAT A",
          teacher: "WANA",
          subject: "Mathematics 5.3 Yr9",
          fullTeacher: "A Wang",
          year: "9",
          colour: "dc5221",
        },
        {
          title: "9 Graphics Technology BY",
          shortTitle: "GRT BY",
          teacher: "HUYD",
          subject: "Graphics Technology Yr9",
          fullTeacher: "D Huynh",
          year: "9",
          colour: "448ae6",
        },
        {
          title: "9 English A",
          shortTitle: "ENG A",
          teacher: "LAUN",
          subject: "English Yr9",
          fullTeacher: "N Lau",
          year: "9",
          colour: "ffd718",
        },
        {
          title: "9 Science A",
          shortTitle: "SCI A",
          teacher: "THEO",
          subject: "Science Yr9",
          fullTeacher: "O The",
          year: "9",
          colour: "2ee8d7",
        },
      ],
      days: {
        "1": {
          dayname: "MonA",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "2": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "3": {
              title: "HIS BX",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "4": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "5": {
              title: "HIS BX",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
          },
          dayNumber: "1",
        },
        "2": {
          dayname: "TueA",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "2": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "502",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "5": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
          },
          dayNumber: "2",
        },
        "3": {
          dayname: "WedA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
            "2": {
              title: "PDH A",
              teacher: "HAYB",
              room: "202",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "3": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "4": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "5": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
          },
          dayNumber: "3",
        },
        "4": {
          dayname: "ThuA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "2": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "502",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "3": {
              title: "HIS BX",
              teacher: "PAUV",
              room: "403",
              fullTeacher: "V Paul",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "4",
        },
        "5": {
          dayname: "FriA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "2": {
              title: "ENG A",
              teacher: "LAUN",
              room: "208",
              fullTeacher: "N Lau",
              year: "9",
            },
            "3": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "4": {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            "5": {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
          },
          dayNumber: "5",
        },
        "6": {
          dayname: "MonB",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "HIS BX",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "2": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "802",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "3": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "4": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "6",
        },
        "7": {
          dayname: "TueB",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "502",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "2": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "203",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "5": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
          },
          dayNumber: "7",
        },
        "8": {
          dayname: "WedB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
            "2": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
            "3": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "4": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "5": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
          },
          dayNumber: "8",
        },
        "9": {
          dayname: "ThuB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "2": {
              title: "SCI A",
              teacher: "THEO",
              room: "301",
              fullTeacher: "O The",
              year: "9",
            },
            "3": {
              title: "HIS BX",
              teacher: "PAUV",
              room: "403",
              fullTeacher: "V Paul",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "9",
        },
        "10": {
          dayname: "FriB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "2": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            "5": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
          },
          dayNumber: "10",
        },
        "11": {
          dayname: "MonC",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "HIS BX",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "2": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "502",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "3": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "4": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "11",
        },
        "12": {
          dayname: "TueC",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "502",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "2": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "3": {
              title: "HIS BX",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "4": {
              title: "GRT BY",
              teacher: "HUYD",
              room: "504",
              fullTeacher: "D Huynh",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "12",
        },
        "13": {
          dayname: "WedC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "2": {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            "3": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "4": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "13",
        },
        "14": {
          dayname: "ThuC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT A",
              teacher: "WANA",
              room: "106",
              fullTeacher: "A Wang",
              year: "9",
            },
            "2": {
              title: "D&T CZ",
              teacher: "GIFR",
              room: "802",
              fullTeacher: "R Gifford",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "14",
        },
        "15": {
          dayname: "FriC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9E",
            teacher: "JACB",
            room: null,
          },
          periods: {
            "1": {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            "2": {
              title: "MAT A",
              teacher: "JAMJ",
              room: "105",
              fullTeacher: "J James",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "5": {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
          },
          dayNumber: "15",
        },
      },
      rollcall: {
        title: "Roll Call 9E",
        shortTitle: "RC 9E",
        teacher: "JACB",
        subject: "Roll Call RC",
        fullTeacher: "B Jackson",
        year: "0",
        colour: "000000",
      },
      advisor: "",
    };

    expect(timetableSchema.parse(timetable)).toMatchSnapshot();
  });

  test("parses a schema with morning periods", () => {
    const timetable = {
      student: {
        surname: "DOE",
        givenname: "John",
        gender: "M",
        DOB: null,
        roll: "RC.9S",
        BoSNumber: null,
        year: "9",
        years: ["9"],
        studentId: "44412345",
      },
      subjects: [
        {
          title: "9 Sport 9",
          shortTitle: "SP 9",
          teacher: null,
          subject: "Sport Yr9",
          fullTeacher: "",
          year: "9",
          colour: "7f5252",
        },
        {
          title: "9 Values Education A",
          shortTitle: "VED A",
          teacher: "PAUV",
          subject: "Values Education Yr9",
          fullTeacher: "V Paul",
          year: "9",
          colour: "640064",
        },
        {
          title: "9 PDHPE A",
          shortTitle: "PDH A",
          teacher: "HAYB",
          subject: "PDHPE Yr9",
          fullTeacher: "B Hayman",
          year: "9",
          colour: "004040",
        },
        {
          title: "9 Commerce CX",
          shortTitle: "COM CX",
          teacher: "ROWJ",
          subject: "Commerce Yr9",
          fullTeacher: "J Rowlands",
          year: "9",
          colour: "008080",
        },
        {
          title: "9 Mathematics 5.3 B",
          shortTitle: "MAT B",
          teacher: "ZHEM",
          subject: "Mathematics 5.3 Yr9",
          fullTeacher: "M Zheng",
          year: "9",
          colour: "dc5221",
        },
        {
          title: "9 Year RST",
          shortTitle: "YA RST",
          teacher: "RICK",
          subject: "Year Adviser",
          fullTeacher: "K Rich",
          year: "9",
          colour: "c0c0c0",
        },
        {
          title: "9 Scripture 9",
          shortTitle: "Scripture 9",
          teacher: "KAYJ",
          subject: "Scripture Yr9",
          fullTeacher: "J Kay",
          year: "9",
          colour: "c0c0c0",
        },
        {
          title: "9 Geography A",
          shortTitle: "GEO A",
          teacher: "STEH",
          subject: "Geography Yr9",
          fullTeacher: "H Stephens",
          year: "9",
          colour: "008080",
        },
        {
          title: "9 English A",
          shortTitle: "ENG A",
          teacher: "LAUN",
          subject: "English Yr9",
          fullTeacher: "N Lau",
          year: "9",
          colour: "ffd718",
        },
        {
          title: "9 Photography & Digital Media CZ",
          shortTitle: "PDM CZ",
          teacher: "STEL",
          subject: "Photography & Digital Media Yr9",
          fullTeacher: "L Stewart",
          year: "9",
          colour: "c488ff",
        },
        {
          title: "9 Science A",
          shortTitle: "SCI A",
          teacher: "THEO",
          subject: "Science Yr9",
          fullTeacher: "O The",
          year: "9",
          colour: "2ee8d7",
        },
        {
          title: "9 History CY",
          shortTitle: "HIS CY",
          teacher: "GENM",
          subject: "History Yr9",
          fullTeacher: "M Genias",
          year: "9",
          colour: "9d9d4f",
        },
      ],
      days: {
        "1": {
          dayname: "MonA",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "2": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "3": {
              title: "COM CX",
              teacher: "ROWJ",
              room: "507",
              fullTeacher: "J Rowlands",
              year: "9",
            },
            "4": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "5": {
              title: "COM CX",
              teacher: "ROWJ",
              room: "507",
              fullTeacher: "J Rowlands",
              year: "9",
            },
          },
          dayNumber: "1",
        },
        "2": {
          dayname: "TueA",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "2": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "5": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
          },
          dayNumber: "2",
        },
        "3": {
          dayname: "WedA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
            "2": {
              title: "PDH A",
              teacher: "HAYB",
              room: "202",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "3": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "4": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "5": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
          },
          dayNumber: "3",
        },
        "4": {
          dayname: "ThuA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "2": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "3": {
              title: "COM CX",
              teacher: "MARD",
              room: "506",
              fullTeacher: "D Marsh",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "4",
        },
        "5": {
          dayname: "FriA",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: [
            {
              title: "Scripture 9",
              teacher: "KAYJ",
              room: null,
              fullTeacher: "J Kay",
              year: "9",
            },
            {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            {
              title: "ENG A",
              teacher: "LAUN",
              room: "208",
              fullTeacher: "N Lau",
              year: "9",
            },
            {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
          ],
          dayNumber: "5",
        },
        "6": {
          dayname: "MonB",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "COM CX",
              teacher: "ROWJ",
              room: "507",
              fullTeacher: "J Rowlands",
              year: "9",
            },
            "2": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "3": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "4": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "6",
        },
        "7": {
          dayname: "TueB",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "2": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "203",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "5": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
          },
          dayNumber: "7",
        },
        "8": {
          dayname: "WedB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
            "2": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
            "3": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "4": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "5": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
          },
          dayNumber: "8",
        },
        "9": {
          dayname: "ThuB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "2": {
              title: "SCI A",
              teacher: "THEO",
              room: "301",
              fullTeacher: "O The",
              year: "9",
            },
            "3": {
              title: "COM CX",
              teacher: "MARD",
              room: "506",
              fullTeacher: "D Marsh",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "9",
        },
        "10": {
          dayname: "FriB",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: [
            {
              title: "Scripture 9",
              teacher: "KAYJ",
              room: null,
              fullTeacher: "J Kay",
              year: "9",
            },
            {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
          ],
          dayNumber: "10",
        },
        "11": {
          dayname: "MonC",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "COM CX",
              teacher: "ROWJ",
              room: "608",
              fullTeacher: "J Rowlands",
              year: "9",
            },
            "2": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "3": {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            "4": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "11",
        },
        "12": {
          dayname: "TueC",
          routine: "0,RC,1,2,R,3,4,MTL1,MTL2,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "2": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "3": {
              title: "COM CX",
              teacher: "ROWJ",
              room: "507",
              fullTeacher: "J Rowlands",
              year: "9",
            },
            "4": {
              title: "HIS CY",
              teacher: "GENM",
              room: "403",
              fullTeacher: "M Genias",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "12",
        },
        "13": {
          dayname: "WedC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "PDH A",
              teacher: "HAYB",
              room: "902",
              fullTeacher: "B Hayman",
              year: "9",
            },
            "2": {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            "3": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "4": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "5": {
              title: "ENG A",
              teacher: "LAUN",
              room: "202",
              fullTeacher: "N Lau",
              year: "9",
            },
          },
          dayNumber: "13",
        },
        "14": {
          dayname: "ThuC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: {
            "1": {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            "2": {
              title: "PDM CZ",
              teacher: "STEL",
              room: "611",
              fullTeacher: "L Stewart",
              year: "9",
            },
            "3": {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            "4": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
            "5": {
              title: "SP 9",
              teacher: null,
              room: null,
              fullTeacher: "",
              year: "9",
            },
          },
          dayNumber: "14",
        },
        "15": {
          dayname: "FriC",
          routine: "0,RC,1,2,R,3,WFL1,WFL2,4,5",
          rollcall: {
            title: "RC 9S",
            teacher: "STEL",
            room: null,
          },
          periods: [
            {
              title: "Scripture 9",
              teacher: "KAYJ",
              room: null,
              fullTeacher: "J Kay",
              year: "9",
            },
            {
              title: "ENG A",
              teacher: "LAUN",
              room: "213",
              fullTeacher: "N Lau",
              year: "9",
            },
            {
              title: "MAT B",
              teacher: "ZHEM",
              room: "102",
              fullTeacher: "M Zheng",
              year: "9",
            },
            {
              title: "SCI A",
              teacher: "THEO",
              room: "702",
              fullTeacher: "O The",
              year: "9",
            },
            {
              title: "GEO A",
              teacher: "STEH",
              room: "506",
              fullTeacher: "H Stephens",
              year: "9",
            },
            {
              title: "VED A",
              teacher: "PAUV",
              room: "205",
              fullTeacher: "V Paul",
              year: "9",
            },
          ],
          dayNumber: "15",
        },
      },
      rollcall: {
        title: "Roll Call 9S",
        shortTitle: "RC 9S",
        teacher: "STEL",
        subject: "Roll Call RC",
        fullTeacher: "L Stewart",
        year: "0",
        colour: "000000",
      },
      advisor: "",
    };

    expect(timetableSchema.parse(timetable)).toMatchSnapshot();
  });
});
